name: dicethrow
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/dice1.png
    - assets/Images/dice2.png
    - assets/Images/dice3.png
    - assets/Images/dice4.png
    - assets/Images/dice5.png
    - assets/Images/dice6.png